name: VS17-CI

on:
  - push
  - pull_request

jobs:
  ci:
    name: windows-vs17
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {gen: Visual Studio 17 2022, arch: x64, config: Release}
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Configure
      run: |
        cmake  -G "${{matrix.gen}}" -A ${{matrix.arch}} -B build
    - name: Build
      run: cmake --build build --config "${{matrix.config}}" --verbose